### ISSUE TITLE
pint-me?

### ISSUE THREAD

**Issue by waynew** [OrkoHunter/ping-me#16]
From the readme:
![pint-me, it's beer:30](https://www.dropbox.com/s/23l4mz72ey4pwzf/Screenshot%202015-12-11%2013.35.41.png?dl=1)
:beers: :trollface:

**Comment by OrkoHunter** [comment]
Yeah that was a typo there! :D Fixed in the code!

**Comment by SanketDG** [comment]
The screenshot is still there, though.
