### ISSUE TITLE
The message flag isn't working !

### ISSUE THREAD

**Issue by makalaaneesh** [OrkoHunter/ping-me#19]
``` python
(dev)makala@aneesh:~/test/ping/ping-me$ ping-me -d December-16-2015 -t 15:20 Get up and eat!
Message is  
Time is  ['15:20', 'Get', 'up', 'and', 'eat!']
Traceback (most recent call last):
  File "/home/makala/test/ping/dev/bin/ping-me", line 9, in <module>
    load_entry_point('ping-me==0.2.1', 'console_scripts', 'ping-me')()
  File "/home/makala/test/ping/dev/local/lib/python2.7/site-packages/ping_me-0.2.1-py2.7.egg/ping_me/ping.py", line 48, in main
    date_time = parser.parse(' '.join(args.DATE) + ' ' + ' '.join(args.TIME))
  File "/home/makala/test/ping/dev/local/lib/python2.7/site-packages/dateutil/parser.py", line 1008, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "/home/makala/test/ping/dev/local/lib/python2.7/site-packages/dateutil/parser.py", line 395, in parse
    raise ValueError("Unknown string format")
ValueError: Unknown string format
```

I printed the `args.message` and `args.TIME` to the console to debug.
I think the argparser argument for message has to be corrected.
Cheers! Really like your project idea.

**Comment by OrkoHunter** [comment]
What about?

```
ping-me Get up and eat -d December-16-2015 -t 15:20
```

`-d` and `-t` are just optional arguments so, that's why the message needs to go just after `ping-me to`.

**Comment by OrkoHunter** [comment]
Also, while using exclamation mark, you'll have to ignore it because shell interprets it for something else. `\!`.
You can skip the `-` between the dates.

**Comment by makalaaneesh** [comment]
`ping-me Get up and eat! -d December-16-2015 -t 15:20` works !

**Comment by OrkoHunter** [comment]
Cool !

**Comment by makalaaneesh** [comment]
@OrkoHunter Hey, i was testing the ping. I get a `200 OK` but i don't get a notification. (I'm running on linux). I checked the inia.txt file on your server which is supposed to contain the text but it's empty.

**Comment by OrkoHunter** [comment]
You have to keep the [`GET.py`](https://github.com/OrkoHunter/ping-me/blob/master/ping_me/GET.py) script file running in your linux. The file is supposed to be empty because the message appears there just for few seconds and then it disappears. The script catches that message for you.

Edit, `$ nohup ./GET.py &`

**Comment by OrkoHunter** [comment]
I am trying to make a chrome extension for the app so that it would be more easy to receive the ping. :)

**Comment by makalaaneesh** [comment]
Oh, nice :) Good luck!
