### ISSUE TITLE
Specify what works and what doesn't

### ISSUE THREAD

**Issue by hargup** [OrkoHunter/ping-me#7]
The project looks interesting and very ambitious, I mean it as a complement. The project is in a very early stage and I guess most of things specified in the README are the things you hope would work. I think you should clearly specify what works and what doesn't.

**Comment by OrkoHunter** [comment]
Sure. I'll update the README very soon. Right now, the basic client-side job is fairly done. I'm just working on the server-side and the database.
Thanks for the complement.
