### ISSUE TITLE
Use pycrypto instead of implement own ad-hoc system

### ISSUE THREAD

**Issue by hargup** [OrkoHunter/ping-me#8]
@OrkoHunter you should use standard crypto librarieslike [pycrypto](https://github.com/dlitz/pycrypto) instead of writing your own ones, later is considered a **very bad** practice.

**Comment by OrkoHunter** [comment]
@hargup Thanks for the suggestion. I didn't know about a library which uses a key for encryption and decryption as well. May I ask if pycrypto supports the key option?

**Comment by hargup** [comment]
Yes, pycrypto supports AES (Advanced Encryption Standard). As the name suggests it is the current standard for symmetric key cryptography (same key for encryption and decryption).

**Comment by OrkoHunter** [comment]
That's cool !

**Comment by kshitij10496** [comment]
PR #11 closes this.
